version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    ignore:
      # Restrict updates to jetty in the 9.4.x space
      - dependency-name: "org.eclipse.jetty:*"
        versions: [ ">=10" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
